---
stages:
  - build
  - lint

default:
  image: php:7.4
  before_script:
    - bash .gitlab/build/docker_install.sh > /dev/null

build-composer-dependencies:
  stage: build
  variables:
    COMPOSER_CACHE_DIR: '.composer'
  script:
    - COMPOSER_CACHE_DIR=.composer
      composer install --prefer-dist --no-progress --optimize-autoloader
  artifacts:
    when: on_success
    expire_in: 2 weeks
    paths:
      - .Build
  cache:
    paths:
      - .composer
      - .Build

php-lint:
  stage: lint
  script:
    - composer ci:php:lint
  allow_failure: true

ts-lint:
  stage: lint
  script:
    - composer ci:ts:lint
  allow_failure: true

json-lint:
  stage: lint
  script:
    - composer ci:json:lint
  allow_failure: true

yaml-lint:
  stage: lint
  script:
    - composer ci:yaml:lint
  allow_failure: true

xliff-lint:
  stage: lint
  script:
    - xmllint --schema .gitlab/build/xliff-core-1.2-strict.xsd
      --noout $(find Resources -name '*.xlf')
  allow_failure: true
