---
stages:
  - build
  - lint
  - code_quality
  - test

include:
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

default:
  before_script:
    - bash .gitlab/build/docker_install.sh > /dev/null
variables:
  MYSQL_ROOT_PASSWORD: root
  typo3DatabaseName: typo3
  typo3DatabaseHost: mariadb
  typo3DatabaseUsername: root
  typo3DatabasePassword: root

build-composer-dependencies:
  image: php:7.4
  stage: build
  variables:
    COMPOSER_CACHE_DIR: '.composer'
  script:
    - COMPOSER_CACHE_DIR=.composer
      composer install --prefer-dist --no-progress --optimize-autoloader
  artifacts:
    when: on_success
    expire_in: 2 weeks
    paths:
      - .Build
  cache:
    paths:
      - .composer
      - .Build

php-lint:
  image: php:7.4
  stage: lint
  script:
    - composer ci:php:lint
  allow_failure: true

ts-lint:
  image: php:7.4
  stage: lint
  script:
    - composer ci:ts:lint
  allow_failure: true

json-lint:
  image: php:7.4
  stage: lint
  script:
    - composer ci:json:lint
  allow_failure: true

xliff-lint:
  image: php:7.4
  stage: lint
  script:
    - xmllint --schema .gitlab/build/xliff-core-1.2-strict.xsd
      --noout $(find Resources -name '*.xlf')
  allow_failure: true

phpcs:
  image: php:7.4
  stage: code_quality
  script:
    - composer ci:php:sniff
  allow_failure: true

unit-tests-php7.4:
  image: php:7.4
  stage: test
  script:
    - composer ci:tests:unit
  allow_failure: true

unit-tests-php7.3:
  image: php:7.3
  stage: test
  script:
    - composer ci:tests:unit
  allow_failure: true

unit-tests-php7.2:
  image: php:7.2
  stage: test
  script:
    - composer ci:tests:unit
  allow_failure: true

functional-tests-php7.4:
  services:
    - mariadb:10
  image: php:7.4
  stage: test
  script:
    - composer ci:tests:functional
  allow_failure: true

functional-tests-php7.3:
  services:
    - mariadb:10
  image: php:7.3
  stage: test
  script:
    - composer ci:tests:functional
  allow_failure: true

functional-tests-php7.2:
  services:
    - mariadb:10
  image: php:7.2
  stage: test
  script:
    - composer ci:tests:functional
  allow_failure: true

security-test:
  image: php:7.4
  stage: test
  script:
    - security-checker security:check
  allow_failure: true