---
stages:
  - build
  - code_quality
  - lint
  - test

include:
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

default:
  image: php:7.4
  before_script:
    - bash .gitlab/build/docker_install.sh > /dev/null

build-composer-dependencies:
  stage: build
  variables:
    COMPOSER_CACHE_DIR: '.composer'
  script:
    - COMPOSER_CACHE_DIR=.composer
      composer install --prefer-dist --no-progress --optimize-autoloader
  artifacts:
    when: on_success
    expire_in: 2 weeks
    paths:
      - .Build
  cache:
    paths:
      - .composer
      - .Build

phpcs:
  stage: code_quality
  script:
    - composer ci:php:sniff

php-lint-php7.2:
  image: php:7.3
  stage: lint
  script:
    - composer ci:php:lint

php-lint-php7.3:
  image: php:7.3
  stage: lint
  script:
    - composer ci:php:lint

php-lint-php7.4:
  image: php:7.4
  stage: lint
  script:
    - composer ci:php:lint

ts-lint:
  stage: lint
  script:
    - composer ci:ts:lint
  allow_failure: true

json-lint:
  stage: lint
  script:
    - composer ci:json:lint
  allow_failure: true

yaml-lint:
  stage: lint
  script:
    - composer ci:yaml:lint
  allow_failure: true

xliff-lint:
  stage: lint
  before_script:
    - wget https://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd
  script:
    - xmllint --schema ./xliff-core-1.2-strict.xsd
      --noout $(find Resources -name '*.xlf')
  allow_failure: true

code_quality:
  before_script: []

eslint-sast:
  before_script: []

phpcs-security-audit-sast:
  before_script: []

secrets-sast:
  before_script: []
