stages:
  - build
  - lint
  - code_quality
  - test

build-composer-dependencies:
  image: php:7.4
  stage: build
  variables:
    COMPOSER_CACHE_DIR: '.composer'
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - COMPOSER_CACHE_DIR=.composer composer install --prefer-dist --no-progress --optimize-autoloader
  tags:
    - docker
  artifacts:
    when: on_success
    expire_in: 2 weeks
    paths:
      - .Build
  cache:
    paths:
      - .composer
      - .Build

php-lint:
  image: php:7.4
  stage: lint
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - composer ci:php:lint
  tags:
    - docker
  allow_failure: true

ts-lint:
  image: php:7.4
  stage: lint
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - composer ci:ts:lint
  tags:
    - docker
  allow_failure: true

phpcs:
  image: php:7.4
  stage: code_quality
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - composer ci:php:sniff
  tags:
    - docker
  allow_failure: true

unit-tests-php7.4:
  image: php:7.4
  stage: test
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - composer ci:tests:unit
  tags:
    - docker
  allow_failure: true
unit-tests-php7.3:
  image: php:7.3
  stage: test
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - composer ci:tests:unit
  tags:
    - docker
  allow_failure: true

functional-tests-php7.4:
  image: php:7.4
  stage: test
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - export typo3DatabaseName="typo3";
    - export typo3DatabaseHost="127.0.0.1";
    - export typo3DatabaseUsername="root";
    - export typo3DatabasePassword="root";
    - composer ci:tests:functional
  tags:
    - docker
  allow_failure: true
functional-tests-php7.3:
  image: php:7.3
  stage: test
  before_script:
    - php -v
    - bash .gitlab/ci/docker_install.sh > /dev/null
  script:
    - export typo3DatabaseName="typo3";
    - export typo3DatabaseHost="127.0.0.1";
    - export typo3DatabaseUsername="root";
    - export typo3DatabasePassword="root";
    - composer ci:tests:functional
  tags:
    - docker
  allow_failure: true