<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tea"
 *
 * Auto generated by Extension Builder 2013-11-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tea example',
	'description' => 'This extension serves as an example on how to unit-test different data types and relation types in TYPO3 extensions.',
	'category' => 'plugin',
	'author' => 'Oliver Klee',
	'author_email' => 'typo3-coding@oliverklee.de',
	'author_company' => 'oliverklee.de',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-7.0.99',
			'fluid' => '6.2.0-7.0.99',
			'typo3' => '6.2.0-7.0.99',
			'phpunit' => '4.0.0-5.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
