.default-frontend:
  image: node:latest
  needs: [ ]
  cache:
    key: "$CI_PROJECT_ID"
    paths:
      - Resources/Private/node_modules/
      - Resources/Private/.npm
  before_script:
    - npm install --cache .npm
